version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/villanono:$CODEBUILD_BUILD_ID .

  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/villanono:$CODEBUILD_BUILD_ID
      - sed 's/%ACCOUNT_ID%/${ACCOUNT_ID}/g' imagedefinitions.json
      - sed 's/%AWS_REGION%/${AWS_REGION}/g' imagedefinitions.json
      - sed 's/%IMAGE_TAG%/${CODEBUILD_BUILD_ID}/g' imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
