version: 0.2

phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/villanono:${IMAGE_TAG} .

  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/villanono:${IMAGE_TAG}
      - sed -i "s/%ACCOUNT_ID%/${ACCOUNT_ID}/g" imagedefinitions.json
      - sed -i "s/%AWS_REGION%/${AWS_REGION}/g" imagedefinitions.json
      - sed -i "s/%IMAGE_TAG%/${IMAGE_TAG}/g" imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
